var images = [
    "positions/afternoonDelight.webp",
    "positions/amazon.webp",
    "positions/ape.webp",
    "positions/ascentToDesire.webp",
    "positions/backwardSlide.webp",
    "positions/balancingAct.webp",
    "positions/Bandoleer.webp",
    "positions/basket.webp",
    "positions/bridge.webp",
    "positions/butterfly.webp",
    "positions/candle.webp",
    "positions/catherineWheel.webp",
    "positions/challenge.webp",
    "positions/clasp.webp",
    "positions/missionary.webp",
    "positions/clip.webp",
    "positions/closeUp.webp",
    "positions/column.webp",
    "positions/crisscross.webp",
    "positions/cross.webp",
    "positions/crossedKeys.webp",
    "positions/crouchingTiger.webp",
    "positions/curledAngle.webp",
    "positions/deckchair.webp",
    "positions/doggyStyle.webp",
    "positions/dolphin.webp",
    "positions/doubleDecker.webp",
    "positions/eagle.webp",
    "positions/eroticV.webp",
    "positions/fan.webp",
    "positions/fold.webp",
    "positions/frog.webp",
    "positions/fromBehind.webp",
    "positions/G-Force.webp",
    "positions/galley.webp",
    "positions/glowingJupiter.webp",
    "positions/glowingTriangle.webp",
    "positions/grip.webp",
    "positions/hero.webp",
    "positions/hinge.webp",
    "positions/hound.webp",
    "positions/indianHeadstand.webp",
    "positions/Indrani.webp",
    "positions/kneel.webp",
    "positions/kneelingWheelbarrow.webp",
    "positions/landslide.webp",
    "positions/lapTop.webp",
    "positions/lotusBlossom.webp",
    "positions/lustfulLeg.webp",
    "positions/magicMountain.webp",
    "positions/mermaid.webp",
    "positions/nirvana.webp",
    "positions/padlock.webp",
    "positions/peg.webp",
    "positions/perch.webp",
    "positions/plough.webp",
    "positions/proneTiger.webp",
    "positions/propeller.webp",
    "positions/proposal.webp",
    "positions/recliningLotus.webp",
    "positions/reverseCowgirl.webp",
    "positions/rider.webp",
    "positions/rightAngle.webp",
    "positions/rock'n'Roller.webp",
    "positions/rockingHorse.webp",
    "positions/rowingBoat.webp",
    "positions/seatedBall.webp",
    "positions/seduction.webp",
    "positions/ship.webp",
    "positions/shoulderHolder.webp",
    "positions/shoulderStand.webp",
    "positions/sidekick.webp",
    "positions/sideSaddle.webp",
    "positions/sidwaysSamba.webp",
    "positions/slide.webp",
    "positions/slip.webp",
    "positions/snail.webp",
    "positions/sphinx.webp",
    "positions/spider.webp",
    "positions/splittingBamboo.webp",
    "positions/squatBalance.webp",
    "positions/stairMaster.webp",
    "positions/standingWheelbarrow.webp",
    "positions/star.webp",
    "positions/super8.webp",
    "positions/supernova.webp",
    "positions/suspendedCongress.webp",
    "positions/suspendedScissors.webp",
    "positions/thighMaster.webp",
    "positions/toad.webp",
    "positions/tominagi.webp",
    "positions/triumphArch.webp",
    "positions/visitor.webp",
    "positions/waterfall.webp",
    "positions/whisper.webp",
    "positions/wideOpened.webp",
    "positions/womanOnTop.webp",
    "positions/X-Rated.webp",
    "positions/Y-Curve.webp",
    "positions/zenPause.webp"

]

var names = [
    "The Afternoon Delight",
    "The Amazon",
    "The Ape",
    "The Ascent To Desire",
    "The Backward Slide",
    "The Balancing Act",
    "The Bandoleer",
    "The Basket",
    "The Bridge",
    "The Butterfly",
    "The Candle",
    "The Catherine Wheel",
    "The Challenge",
    "The Clasp",
    "Missionary",
    "The Clip",
    "The Close Up",
    "The Column",
    "The Crisscross",
    "The Cross",
    "The Crossed Keys",
    "The Crouching Tiger",
    "The Curled Angle",
    "The Deckchair",
    "Doggy Style",
    "The Dolphin",
    "The Double Decker",
    "The Eagle",
    "The Erotic V",
    "The Fan",
    "The Fold",
    "The Frog",
    "The From Behind",
    "The G-Force",
    "The Galley",
    "The Glowing Jupiter",
    "The Glowing Triangle",
    "The Grip",
    "The Hero",
    "The Hinge",
    "The Hound",
    "The Indian Headstand",
    "The Indrani",
    "The Kneel",
    "The Kneeling Wheelbarrow",
    "The Landslide",
    "The Lap Top",
    "The Lotus Blossom",
    "The Lustful Leg",
    "The Magic Mountain",
    "The Mermaid",
    "The Nirvana",
    "The Padlock",
    "The Peg",
    "The Perch",
    "The Plough",
    "The Prone Tiger",
    "The Propeller",
    "The Proposal",
    "The Reclining Lotus",
    "The Reverse Cowgirl",
    "The Rider",
    "The Right Angle",
    "The Rock 'N' Roller",
    "The Rocking Horse",
    "The Rowing Boat",
    "The Seated Ball",
    "The Seduction",
    "The Ship",
    "The Shoulder Holder",
    "The Shoulder Stand",
    "The Sidekick",
    "The Side Saddle",
    "The Sidways Samba",
    "The Slide",
    "The Slip",
    "The Snail",
    "The Sphinx",
    "The Spider",
    "The Splitting Bamboo",
    "The Squat Balance",
    "The Stair Master",
    "The Standing Wheelbarrow",
    "The Star",
    "The Super8",
    "The Supernova",
    "The Suspended Congress",
    "The Suspended Scissors",
    "The Thigh Master",
    "The Toad",
    "The Tominagi",
    "The Triumph Arch",
    "The Visitor",
    "The Waterfall",
    "The Whisper",
    "The Wide Opened",
    "The Woman On Top",
    "The X-Rated",
    "The Y-Curve",
    "The Zen Pause"
    
]

function generate() {

    var x = Math.floor(Math.random() * images.length);
    //x=72
    document.getElementById("image").src = images[x];
    document.getElementById("positionName").innerHTML = names[x];
    console.log(names[x], x);
    
    
}